In [0]:
from __future__ import print_function
import torch

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[1.8424e-36, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 2.8026e-45],
        [0.0000e+00, 1.1210e-44, 0.0000e+00],
        [1.4013e-45, 0.0000e+00, 0.0000e+00]])


In [3]:
type(x)

torch.Tensor

In [4]:
x = torch.rand(5, 3)
print(x)

tensor([[0.8421, 0.2867, 0.4995],
        [0.8733, 0.7475, 0.0804],
        [0.8316, 0.7290, 0.2356],
        [0.8245, 0.6507, 0.8146],
        [0.3648, 0.1049, 0.2555]])


In [8]:
x = torch.ones(5, 3, dtype=torch.long)
print(x)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])


In [7]:
type(x)

torch.Tensor

In [19]:
 x= torch.tensor([(5.5, 3,2),(1,2,3),(2,3,4)])
print(x)

tensor([[5.5000, 3.0000, 2.0000],
        [1.0000, 2.0000, 3.0000],
        [2.0000, 3.0000, 4.0000]])


In [20]:
type(x)

torch.Tensor

In [0]:
x = x.new_ones(5, 3, dtype=torch.double)

In [0]:
y=torch.ones(5,3,dtype=torch.double)

In [27]:
y

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [23]:
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [28]:
x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)

tensor([[-1.6986, -0.4886, -1.1478],
        [ 0.3308, -1.2005, -1.2701],
        [-0.2655,  2.7079, -0.5001],
        [ 0.3350,  0.7669,  0.0399],
        [-0.8688, -0.2449, -0.6753]])


In [31]:
torch.add(x,y)

tensor([[-0.6986,  0.5114, -0.1478],
        [ 1.3308, -0.2005, -0.2701],
        [ 0.7345,  3.7079,  0.4999],
        [ 1.3350,  1.7669,  1.0399],
        [ 0.1312,  0.7551,  0.3247]], dtype=torch.float64)

In [32]:
x.add_(10)

tensor([[ 8.3014,  9.5114,  8.8522],
        [10.3308,  8.7995,  8.7299],
        [ 9.7345, 12.7079,  9.4999],
        [10.3350, 10.7669, 10.0399],
        [ 9.1312,  9.7551,  9.3247]])

In [29]:
x.size()

torch.Size([5, 3])

In [35]:
x = torch.randn(4, 4)
y = x.view(16)
y

tensor([-0.2151,  0.3548, -0.0776, -0.4599,  0.9263, -0.4289,  1.0579, -0.8223,
        -0.3644,  1.0584, -0.8114, -0.2857,  0.5531,  1.0141, -1.2714,  1.0289])

In [36]:
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
z

tensor([[-0.2151,  0.3548, -0.0776, -0.4599,  0.9263, -0.4289,  1.0579, -0.8223],
        [-0.3644,  1.0584, -0.8114, -0.2857,  0.5531,  1.0141, -1.2714,  1.0289]])

In [39]:
import numpy as np
a = np.ones(9)
b = torch.from_numpy(a)
np.add(a, 10, out=a)
print(a)
print(b)

[11. 11. 11. 11. 11. 11. 11. 11. 11.]
tensor([11., 11., 11., 11., 11., 11., 11., 11., 11.], dtype=torch.float64)


In [0]:
v=torch.ones(3)

In [42]:
v+3

tensor([4., 4., 4.])

In [43]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [0]:
y=x*3

In [51]:
y.mean()

tensor(3., grad_fn=<MeanBackward0>)

In [0]:
#Derivaive

In [53]:
x = torch.autograd.Variable(torch.Tensor([2]),requires_grad=True)
x

tensor([2.], requires_grad=True)

In [0]:
y = 5*x**4 + 3*x**3 + 7*x**2 + 9*x - 5
y.backward()


In [56]:
x.grad

tensor([233.])